WIP: Expose all adresses and gateways as environment variables
ifupdown-ng/ifupdown-ng pull request #100
Opened 2020-10-04 01:17 UTC by BarbarossaTM

Gather all IP addresses and gateways and expose them as `IF_ADDRESSES` and
`IF_GATEWAYS` environment variables to executors. This eliminates the need
to run ifquery from execuctors which would have to parse the config file
again on every run.

2020-10-05 20:33 UTC, kaniini requested changes

2020-10-05 20:33 UTC, kaniini commented on libifupdown/lifecycle.c
> +		printf ("Doubling buffer...\n");
Remove this debug statement.

2020-10-05 20:33 UTC, kaniini commented on libifupdown/lifecycle.c
> +	size_t printed = sprintf (*end, "%s ", value);
Use `snprintf` here with calcullated size.

2020-10-05 20:33 UTC, kaniini commented on libifupdown/lifecycle.c
> +		lif_environment_push(envp, "IF_ADDRESSES", addresses);
after `addresses` and `gateways` is copied to environment, we should `free()` it to prevent a memory leak.

2020-10-06 00:55 UTC, BarbarossaTM commented on libifupdown/lifecycle.c
> +		printf ("Doubling buffer...\n");
Shit, good catch!

2020-10-06 03:46 UTC, merged